version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
            
    angular-service: 
        container_name: angularcontainer 
        build: ./angularfront 
        volumes: 
            - './angularfront:/usr/src/app' 
        ports: 
            - '4200:4200'
        command: > 
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"